Repository nestjs/docs.nestjs.com, pull requests merged in 2019-02, with the labels that each got.

#193 Make headers linkable (#88)
  src/app/app.module.ts
  src/app/common/directives/header-anchor.directive.ts
  src/app/homepage/homepage.component.scss
Labels: feature

#198 feat(docs): Add nest/terminus documentation
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/homepage/menu/menu.component.ts
  src/app/homepage/pages/recipes/terminus/terminus.component.html
  src/app/homepage/pages/recipes/terminus/terminus.component.ts
  src/app/homepage/pages/recipes/terminus/terminus.spec.ts
Labels: content, type: tutorial

#214 docs: add Documentation tool entry
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/homepage/menu/menu.component.ts
  src/app/homepage/pages/faq/documentation/documentation.component.html
  src/app/homepage/pages/faq/documentation/documentation.component.ts
  src/assets/documentation-compodoc-1.jpg
  src/assets/documentation-compodoc-2.jpg
Labels: content, type: tutorial

#182 Added iflix logo to discover page
  src/app/homepage/pages/discover/who-uses/who-uses.component.ts
  src/assets/logo/iflix.svg
Labels: content
